---
title: "Group Assignment 3 - Creative Gaming"
author:
- Section 51
- Gaurav Agrawal, Ajitesh Abhishek, Tarun Joshi
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
---

```{r, include=FALSE}
### Determine notebook defaults:
knitr::opts_chunk$set(echo=TRUE,      # Print all the code in all the chunks
                      warning=FALSE,  # Don't print warning statements
                      message=FALSE,  # Don't print other R output messages
                      comment=NA)     # Helps produce prettier output
```

```{r pkginit, echo=FALSE, message=FALSE}
# Install packages needed for class
options(install.packages.check.source = "no")
pkgs = c('rmarkdown', 'gmodels', 'modelr', 'janitor', 'haven', 'readxl', 'knitr', 'psych', 'statar', 'tidyverse', 'devtools', 'lfe', 'Matrix')
pkgs.installed = installed.packages()[, 'Package']
needtoinstall = setdiff(pkgs, pkgs.installed)
if (length(needtoinstall) > 0)
    install.packages(needtoinstall)
devtools::install_github("fzettelmeyer/mktg482", upgrade = "never", force = TRUE)

```

```{r, echo=FALSE, message = FALSE, warning = FALSE}
### Load packages:
library(gmodels)
library(modelr)
library(janitor)
library(haven)
library(readxl)
library(knitr)
library(psych)
library(statar)
library(tidyverse)
library(mktg482)
library(sjPlot)
library(skimr) 
library(nnet)
library(tictoc)
library(effects)
library(splitstackshape)
library(tools4uplift)
library(ranger)
```

### Read in the data:
```{r}
# use load("filename.Rdata") for .Rdata files
data = load("creative_gaming_propensity.Rdata")
```

### Part 1 - Question a
```{r}
cg_ad_random <- cg_ad_treatment[sample_random_30000,]

```

### Part 1 - Question b
```{r}
expdata_stacked <- rbind(cg_organic_control %>% mutate(ad = 0), cg_ad_random %>% mutate(ad = 1))
```


### Part 1 - Question c
```{r}
set.seed(1234)
split.index <- stratified(expdata_stacked, c("ad",
 "converted"), 0.7, bothSets=TRUE)
expdata_stacked.train <- split.index[[1]]
expdata_stacked.test <- split.index[[2]]
```
The training test split is 70:30


### Part 2 
```{r}
fm <- formula(converted ~. -ad)
logit.treat <- glm(fm, data=(expdata_stacked.train%>%filter(ad==1)), family = "binomial")
logit.control <- glm(fm, data=(expdata_stacked.train%>%filter(ad==0)), family = "binomial")
```


```{r}
score_treat <- predict(logit.treat, newdata = expdata_stacked.test, type="response")
score_control <- predict(logit.control, newdata = expdata_stacked.test, type="response")
```

```{r}
expdata_stacked.test <- expdata_stacked.test%>%
  mutate(score_treat = score_treat,
         score_control = score_control,
         score_uplift = score_treat-score_control)
```

```{r}
expdata_stacked.test%>%
  arrange(-score_uplift)%>%
  select(converted, ad, score_treat, score_control, score_uplift)%>%
  head()
```

### Part 3 
```{r}
PerfectTable_uplift <-
  QiniTable(
    expdata_stacked.test,
    treat ="ad",
    outcome="converted",
    prediction = "score_uplift",
    nb.group=20
  )

PerfectTable_uplift
```

```{r}
QiniCurve(PerfectTable_uplift)
```

```{r}
QiniBarPlot(PerfectTable_uplift)
```
As per the plots, we have maximum incremental uplift till 25% (average uplift of 20%). Overall, we see uplift in the 90% of the customers, and for the bottom 10% there is destruction of value.


## Question 5
```{r}
PerfTable_propensity <-
QiniTable(
expdata_stacked.test,
treat = "ad",
outcome = "converted",
prediction = "score_treat",
nb.group = 20
)
PerfTable_propensity
```

```{r}
QiniBarPlot(PerfTable_propensity)

```

```{r}
QiniBarPlot2(PerfectTable_uplift, PerfTable_propensity, modelnames = c("Uplift Model", "Propensity Model"))
```

## Question 6

```{r}

```

## Part 2: Question 1
```{r}
fm <- formula(converted ~. -ad)

random.treat <- ranger(fm, data=(expdata_stacked.train %>% filter(ad==1)), probability = TRUE)
random.control <- ranger(fm, data=(expdata_stacked.train %>% filter(ad==0)), probability = TRUE)

```

```{r}
score_treat_rf <- predict(random.treat, data = expdata_stacked.test, type ="response")[[1]][,2]
score_control_rf <- predict(random.control, data = expdata_stacked.test, type ="response")[[1]][,2]
```

```{r}
expdata_stacked.test_rf <- expdata_stacked.test%>%
  mutate(score_treat_rf = score_treat_rf,
         score_control_rf = score_control_rf,
         score_uplift_rf = score_treat-score_control)
```

```{r}
expdata_stacked.test_rf%>%
  arrange(-score_uplift_rf)%>%
  select(converted, ad, score_treat_rf, score_control_rf, score_uplift_rf)%>%
  head()
```
```{r}
PerfectTable_uplift_rf <-
  QiniTable(
    expdata_stacked.test_rf,
    treat ="ad",
    outcome="converted",
    prediction = "score_uplift_rf",
    nb.group=20
  )

PerfectTable_uplift_rf

```
```{r}
PerfTable_propensity_rf <-
QiniTable(
expdata_stacked.test_rf,
treat = "ad",
outcome = "converted",
prediction = "score_treat_rf",
nb.group = 20
)
PerfTable_propensity_rf
```

```{r}
par(mfrow=c(1,2))
QiniBarPlot2(PerfectTable_uplift_rf, PerfTable_propensity_rf, modelnames = c("Uplift Model RF", "Propensity Model RF"))
QiniBarPlot2(PerfectTable_uplift, PerfTable_propensity, modelnames = c("Uplift Model", "Propensity Model"))
```

